/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fhdw.jjtt.w.WRuntimeModule;
import de.fhdw.jjtt.w.WStandaloneSetup;
import de.fhdw.jjtt.w.ide.WIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WIdeSetup extends WStandaloneSetup {
  @Override
  public Injector createInjector() {
    WRuntimeModule _wRuntimeModule = new WRuntimeModule();
    WIdeModule _wIdeModule = new WIdeModule();
    return Guice.createInjector(Modules2.mixin(_wRuntimeModule, _wIdeModule));
  }
}
