/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWScopeProvider extends DelegatingScopeProvider {
}
