/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.tests

import com.google.inject.Inject
import de.fhdw.jjtt.w.w.Program
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(WInjectorProvider)
class WParsingTest {
	@Inject
	ParseHelper<Program> parseHelper

	@Test
	def void loadModel() {
//		val result = parseHelper.parse('''
//			x1 = x0 + 5;
//			WHILE x1 != 0 DO
//				x2 := x2 + 8;
//				x1 := x1 - 1;
//			ENDWHILE
//		''')
		val result2 = parseHelper.parse('''
			While x != 6 do
			y = x + 2
			endwhile ;
			x = y + 8
		''')
		println(result2)
		Assert.assertNotNull(result2)
		Assert.assertTrue(result2.eResource.errors.isEmpty)
//		println(result)
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
