/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.ui;

import de.fhdw.jjtt.w.ui.AbstractWUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WUiModule extends AbstractWUiModule {
  public WUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
