/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.scoping;

import de.fhdw.jjtt.w.scoping.AbstractWScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class WScopeProvider extends AbstractWScopeProvider {
}
