/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.tests;

import com.google.inject.Inject;
import de.fhdw.jjtt.w.tests.WInjectorProvider;
import de.fhdw.jjtt.w.w.Program;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(WInjectorProvider.class)
@SuppressWarnings("all")
public class WParsingTest {
  @Inject
  private ParseHelper<Program> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("While x != 6 do");
      _builder.newLine();
      _builder.append("y = x + 2");
      _builder.newLine();
      _builder.append("endwhile ;");
      _builder.newLine();
      _builder.append("x = y + 8");
      _builder.newLine();
      final Program result2 = this.parseHelper.parse(_builder);
      InputOutput.<Program>println(result2);
      Assert.assertNotNull(result2);
      Assert.assertTrue(result2.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
