/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.w;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.jjtt.w.w.Assignment#getToBeAssigned <em>To Be Assigned</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Assignment#getVar <em>Var</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Assignment#getOp <em>Op</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Assignment#getConst <em>Const</em>}</li>
 * </ul>
 *
 * @see de.fhdw.jjtt.w.w.WPackage#getAssignment()
 * @model
 * @generated
 */
public interface Assignment extends Program
{
  /**
   * Returns the value of the '<em><b>To Be Assigned</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Be Assigned</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Be Assigned</em>' containment reference.
   * @see #setToBeAssigned(Variable)
   * @see de.fhdw.jjtt.w.w.WPackage#getAssignment_ToBeAssigned()
   * @model containment="true"
   * @generated
   */
  Variable getToBeAssigned();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Assignment#getToBeAssigned <em>To Be Assigned</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Be Assigned</em>' containment reference.
   * @see #getToBeAssigned()
   * @generated
   */
  void setToBeAssigned(Variable value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Variable)
   * @see de.fhdw.jjtt.w.w.WPackage#getAssignment_Var()
   * @model containment="true"
   * @generated
   */
  Variable getVar();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Assignment#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variable value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see de.fhdw.jjtt.w.w.WPackage#getAssignment_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Assignment#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Const</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' containment reference.
   * @see #setConst(Constant)
   * @see de.fhdw.jjtt.w.w.WPackage#getAssignment_Const()
   * @model containment="true"
   * @generated
   */
  Constant getConst();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Assignment#getConst <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' containment reference.
   * @see #getConst()
   * @generated
   */
  void setConst(Constant value);

} // Assignment
