/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.w;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.jjtt.w.w.Loop#getVar <em>Var</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Loop#getConst <em>Const</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Loop#getProg <em>Prog</em>}</li>
 * </ul>
 *
 * @see de.fhdw.jjtt.w.w.WPackage#getLoop()
 * @model
 * @generated
 */
public interface Loop extends Program
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Variable)
   * @see de.fhdw.jjtt.w.w.WPackage#getLoop_Var()
   * @model containment="true"
   * @generated
   */
  Variable getVar();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Loop#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variable value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Const</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' containment reference.
   * @see #setConst(Constant)
   * @see de.fhdw.jjtt.w.w.WPackage#getLoop_Const()
   * @model containment="true"
   * @generated
   */
  Constant getConst();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Loop#getConst <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' containment reference.
   * @see #getConst()
   * @generated
   */
  void setConst(Constant value);

  /**
   * Returns the value of the '<em><b>Prog</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prog</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prog</em>' containment reference.
   * @see #setProg(Program)
   * @see de.fhdw.jjtt.w.w.WPackage#getLoop_Prog()
   * @model containment="true"
   * @generated
   */
  Program getProg();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Loop#getProg <em>Prog</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prog</em>' containment reference.
   * @see #getProg()
   * @generated
   */
  void setProg(Program value);

} // Loop
