/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.w;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.fhdw.jjtt.w.w.WFactory
 * @model kind="package"
 * @generated
 */
public interface WPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "w";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fhdw.de/jjtt/w/W";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "w";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WPackage eINSTANCE = de.fhdw.jjtt.w.w.impl.WPackageImpl.init();

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.ProgramImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.AssignmentImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 1;

  /**
   * The feature id for the '<em><b>To Be Assigned</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__TO_BE_ASSIGNED = PROGRAM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VAR = PROGRAM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__OP = PROGRAM_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__CONST = PROGRAM_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = PROGRAM_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.VariableImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.ConstantImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.LoopImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 4;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__VAR = PROGRAM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__CONST = PROGRAM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Prog</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__PROG = PROGRAM_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = PROGRAM_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link de.fhdw.jjtt.w.w.impl.SequenceImpl <em>Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.fhdw.jjtt.w.w.impl.SequenceImpl
   * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getSequence()
   * @generated
   */
  int SEQUENCE = 5;

  /**
   * The feature id for the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__P1 = PROGRAM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__P2 = PROGRAM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_FEATURE_COUNT = PROGRAM_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see de.fhdw.jjtt.w.w.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see de.fhdw.jjtt.w.w.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Assignment#getToBeAssigned <em>To Be Assigned</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To Be Assigned</em>'.
   * @see de.fhdw.jjtt.w.w.Assignment#getToBeAssigned()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_ToBeAssigned();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Assignment#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see de.fhdw.jjtt.w.w.Assignment#getVar()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Var();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.jjtt.w.w.Assignment#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see de.fhdw.jjtt.w.w.Assignment#getOp()
   * @see #getAssignment()
   * @generated
   */
  EAttribute getAssignment_Op();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Assignment#getConst <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Const</em>'.
   * @see de.fhdw.jjtt.w.w.Assignment#getConst()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Const();

  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see de.fhdw.jjtt.w.w.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.jjtt.w.w.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.fhdw.jjtt.w.w.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see de.fhdw.jjtt.w.w.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link de.fhdw.jjtt.w.w.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.fhdw.jjtt.w.w.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Value();

  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see de.fhdw.jjtt.w.w.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Loop#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see de.fhdw.jjtt.w.w.Loop#getVar()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Var();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Loop#getConst <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Const</em>'.
   * @see de.fhdw.jjtt.w.w.Loop#getConst()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Const();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Loop#getProg <em>Prog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prog</em>'.
   * @see de.fhdw.jjtt.w.w.Loop#getProg()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Prog();

  /**
   * Returns the meta object for class '{@link de.fhdw.jjtt.w.w.Sequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sequence</em>'.
   * @see de.fhdw.jjtt.w.w.Sequence
   * @generated
   */
  EClass getSequence();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Sequence#getP1 <em>P1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P1</em>'.
   * @see de.fhdw.jjtt.w.w.Sequence#getP1()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_P1();

  /**
   * Returns the meta object for the containment reference '{@link de.fhdw.jjtt.w.w.Sequence#getP2 <em>P2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P2</em>'.
   * @see de.fhdw.jjtt.w.w.Sequence#getP2()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_P2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WFactory getWFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.ProgramImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.AssignmentImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>To Be Assigned</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__TO_BE_ASSIGNED = eINSTANCE.getAssignment_ToBeAssigned();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__VAR = eINSTANCE.getAssignment_Var();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT__OP = eINSTANCE.getAssignment_Op();

    /**
     * The meta object literal for the '<em><b>Const</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__CONST = eINSTANCE.getAssignment_Const();

    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.VariableImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.ConstantImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__VALUE = eINSTANCE.getConstant_Value();

    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.LoopImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__VAR = eINSTANCE.getLoop_Var();

    /**
     * The meta object literal for the '<em><b>Const</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__CONST = eINSTANCE.getLoop_Const();

    /**
     * The meta object literal for the '<em><b>Prog</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__PROG = eINSTANCE.getLoop_Prog();

    /**
     * The meta object literal for the '{@link de.fhdw.jjtt.w.w.impl.SequenceImpl <em>Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.fhdw.jjtt.w.w.impl.SequenceImpl
     * @see de.fhdw.jjtt.w.w.impl.WPackageImpl#getSequence()
     * @generated
     */
    EClass SEQUENCE = eINSTANCE.getSequence();

    /**
     * The meta object literal for the '<em><b>P1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__P1 = eINSTANCE.getSequence_P1();

    /**
     * The meta object literal for the '<em><b>P2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__P2 = eINSTANCE.getSequence_P2();

  }

} //WPackage
