/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.tests;

import com.google.inject.Inject;
import de.fhdw.jjtt.w.tests.WInjectorProvider;
import de.fhdw.jjtt.w.w.Program;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(WInjectorProvider.class)
@SuppressWarnings("all")
public class WParsingTest {
  @Inject
  private ParseHelper<Program> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("x1 = x0 + 5;");
      _builder.newLine();
      _builder.append("WHILE x1 != 0 DO");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("x2 := x2 + 8;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("x1 := x1 - 1;");
      _builder.newLine();
      _builder.append("ENDWHILE");
      _builder.newLine();
      final Program result = this.parseHelper.parse(_builder);
      InputOutput.<Program>println(result);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
