/*
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.ui.tests;

import com.google.inject.Injector;
import de.fhdw.jjtt.w.ui.internal.WActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WActivator.getInstance().getInjector("de.fhdw.jjtt.w.W");
	}

}
