/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w.ide;

import de.fhdw.jjtt.w.ide.AbstractWIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WIdeModule extends AbstractWIdeModule {
}
