/**
 * generated by Xtext 2.12.0
 */
package de.fhdw.jjtt.w;

import de.fhdw.jjtt.w.AbstractWRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WRuntimeModule extends AbstractWRuntimeModule {
}
