/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w;

import de.fhdw.jjtt.w.WStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WStandaloneSetup extends WStandaloneSetupGenerated {
  public static void doSetup() {
    new WStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
