/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/fhdw/jjtt/w/parser/antlr/internal/InternalWParser.tokens");
	}
}
