/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.parser.antlr;

import com.google.inject.Inject;
import de.fhdw.jjtt.w.parser.antlr.internal.InternalWParser;
import de.fhdw.jjtt.w.services.WGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WParser extends AbstractAntlrParser {

	@Inject
	private WGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWParser createParser(XtextTokenStream stream) {
		return new InternalWParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public WGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
