/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.ide

import com.google.inject.Guice
import de.fhdw.jjtt.w.WRuntimeModule
import de.fhdw.jjtt.w.WStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class WIdeSetup extends WStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new WRuntimeModule, new WIdeModule))
	}
	
}
