/*
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.ui;

import com.google.inject.Injector;
import de.fhdw.jjtt.w.ui.internal.WActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(WActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		WActivator activator = WActivator.getInstance();
		return activator != null ? activator.getInjector(WActivator.DE_FHDW_JJTT_W_W) : null;
	}

}
