/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.w;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fhdw.jjtt.w.w.WPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
} // Program
