/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.w;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fhdw.jjtt.w.w.Sequence#getP1 <em>P1</em>}</li>
 *   <li>{@link de.fhdw.jjtt.w.w.Sequence#getP2 <em>P2</em>}</li>
 * </ul>
 *
 * @see de.fhdw.jjtt.w.w.WPackage#getSequence()
 * @model
 * @generated
 */
public interface Sequence extends Program
{
  /**
   * Returns the value of the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>P1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>P1</em>' containment reference.
   * @see #setP1(Program)
   * @see de.fhdw.jjtt.w.w.WPackage#getSequence_P1()
   * @model containment="true"
   * @generated
   */
  Program getP1();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Sequence#getP1 <em>P1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P1</em>' containment reference.
   * @see #getP1()
   * @generated
   */
  void setP1(Program value);

  /**
   * Returns the value of the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>P2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>P2</em>' containment reference.
   * @see #setP2(Program)
   * @see de.fhdw.jjtt.w.w.WPackage#getSequence_P2()
   * @model containment="true"
   * @generated
   */
  Program getP2();

  /**
   * Sets the value of the '{@link de.fhdw.jjtt.w.w.Sequence#getP2 <em>P2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P2</em>' containment reference.
   * @see #getP2()
   * @generated
   */
  void setP2(Program value);

} // Sequence
