/**
 * generated by Xtext 2.13.0
 */
package de.fhdw.jjtt.w.validation;

import de.fhdw.jjtt.w.validation.AbstractWValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WValidator extends AbstractWValidator {
}
